theme: jekyll-theme-minimal
title: Bioinformatics BIMM 143 s18
description: My personal repo for projects from this class
logo: https://t4.ftcdn.net/jpg/01/29/43/81/500_F_129438187_NNtnMvkEsUsbyoUoCxgVg0keuikF22oF.jpg
