---
title: "class16-InSeq_Practice"
author: "Vaibhav Menon"
date: "5/24/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Let's load the required libraries for this section
```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(readr)
```

Let;s load the data file for analsysis
```{r}
exp_data <- read.csv("Experimental_results.csv")
head(exp_data)
```
```{r}
#Remove unnecessary column "X" from dataframe
exp_data <- select(exp_data, -X)
head(exp_data)
```

```{r}
#Create table with mutation, strain, and environment info
mut_str_env <- select(exp_data, Mut_ID, Strain, Environment)
head(mut_str_env)
```
```{r}
#Rearrange data to have time and frequency as columns for ggplot use
exp_rearranged <- gather(exp_data, Generation, Frequency, H_0:H_96)
head(exp_rearranged)
```
```{r}
# Separate values in "Generation" column into 2 columns
table_for_graph<-separate(exp_rearranged,Generation,into=c("H","Time"))
head(table_for_graph)
```

```{r}
# Remove column "H" using function "select"
table_for_graph<-select(table_for_graph, -H)
head(table_for_graph)
```

```{r}
#Remove NA's and turn time column values into numeric values 
table_cleaned <- na.omit(table_for_graph)
table_cleaned$Time <- as.numeric(table_cleaned$Time)
head(table_cleaned)
```
```{r}
ggplot(table_cleaned)+geom_line(aes(x=Time,y=Frequency,group=BC_ID),alpha=.05,colour="#000189")+facet_grid(.~Strain)+ggtitle("Barcode trajectories")+theme(plot.title = element_text(hjust = 0.5))+xlab("Time, hours") + ylab("Log10(Barcode frequency)")
```

```{r}
#visualize How a randomly selected mutation behaves
mut34<-filter(table_cleaned, table_cleaned$Mut_ID=="34")
mut34
ggplot(mut34,aes(Time, Frequency, group=BC_ID, color=BC_ID))+geom_line()+theme(legend.position="none")+facet_grid(.~Strain)+ggtitle("Mutation_34")+xlab("Time, hours") + ylab("Log10(Barcode frequency)")+theme(plot.title = element_text(hjust = 0.5))
```

```{r}
#Filter out sequencing noise and plot again
mut34_f<-filter(mut34, mut34$Frequency>(-5))
mut34_f
ggplot(mut34_f,aes(Time, Frequency, group=BC_ID, color=BC_ID))+geom_line()+theme(legend.position="none")+facet_grid(.~Strain)+ggtitle("Mutation_34")+xlab("Time, hours") + ylab("Log10(Barcode frequency)")+theme(plot.title = element_text(hjust = 0.5))
```
```{r}
ggplot(mut34_f,aes(Time, Frequency, colour = BC_ID, group=BC_ID))+geom_point()+geom_smooth(se = FALSE, method = "lm")+facet_grid(.~Strain)+theme(legend.position="none")+ggtitle(paste("Mutation",34, sep="_"))+xlab("Time, hours")+ ylab("Log10(Barcode frequency)")
```
```{r}
#take the filtered data for mutation 34 (mut34_f) and filter out information about one barcode you like

# BC_ID=25361 in DivAnc strain
BC_25361<-filter(mut34_f, mut34_f$BC_ID=="25361", mut34_f$Strain=="DivAnc")
BC_25361
```

```{r}
#plot frequency of this barcode:
ggplot(BC_25361,aes(Time, Frequency, colour = BC_ID))+geom_point()+theme(legend.position="none")+ggtitle("BC_25361")+xlab("Time, hours") + ylab("Log10(Frequency)")
```

```{r}
#use lm function to fit the line to these points:
ggplot(BC_25361,aes(Time, Frequency, colour = BC_ID))+geom_point()+geom_smooth(se = FALSE, method = "lm")+theme(legend.position="none")+ggtitle("BC_25361")+xlab("Time, hours") + ylab("Log10(Frequency)")
```

```{r}
#check what data lm function returns:
regression_model<-lm(Frequency~Time,BC_25361)
summary_data<-summary(regression_model)
summary_data
```
```{r}
#The information we are interested in is the value of Slopeand Intercept of this line:
# Let's try to access them:

# Time
Time<-summary_data$coefficients[2]
Time

# Intercept:
Intercept<-summary_data$coefficients[1]
Intercept
```

